# Generated by Django 5.0.2 on 2024-02-11 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_rename_project_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=100, unique=True)),
                ('field_input_data', models.TextField()),
                ('selection_box_data', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('form_input_field_data', models.TextField(default='')),
                ('redirect_path_input_field', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formapp.form'),
        ),
    ]
