# Generated by Django 4.2.5 on 2024-02-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_draggableinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggableinput',
            name='x_axis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='y_axis',
            field=models.FloatField(),
        ),
    ]
