# Generated by Django 4.2.5 on 2024-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_draggableinput_input_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggableinput',
            name='input_id',
            field=models.IntegerField(unique=True),
        ),
    ]
