# Generated by Django 4.2.5 on 2024-02-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_alter_draggableinput_input_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draggableinput',
            old_name='input_id',
            new_name='field_id',
        ),
    ]
